### ISSUE TITLE
Wildtype/mutant seq columns are incorrectly named in  V2 train and test files

### ISSUE THREAD

**Issue by atamazian** [JinyuanSun/mutation-stability-data#1]
Wildtype/mutant seq columns are incorrectly named in  V2 train and test files - `wt_seq` should be renamed to `mut_seq`, and `mut_seq` should be renamed to `wt_seq`, since the same sequence for each PDB ID code should be in `wt_seq` column, not in `mut_seq` column (like in V1).

**Comment by JinyuanSun** [comment]
Yes, sorry for this huge mistake.

**Comment by JinyuanSun** [comment]
> Yes, sorry for this huge mistake.

Just fixed. Thanks for reporting this issue.

**Comment by atamazian** [comment]
Thank you!
